name: Update Data Repo
on: workflow_call
jobs:
  download-bigquery-agg:
    runs-on: ubuntu-latest
    steps:
      - id: "checkout"
        uses: "actions/checkout@v3"
      - id: "python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - id: "pip"
        run: pip install .
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.bq }}
      - id: "download"
        run: "python3 -m cruxdownloader data/global"
